/**
 * /api/products/[id]/documents/[documentId]/download
 *
 * GET — Serves a private compliance document via a time-limited signed token.
 *
 * SECURITY MODEL:
 * - Documents are stored in uploads/private/ and are NEVER publicly accessible.
 * - Access requires a valid HMAC-signed token generated by the list or upload endpoint.
 * - Tokens expire after 15 minutes.
 * - The token binds together: documentId + storageReference + userId + expiresAt.
 * - Any tampering with the token causes an immediate 403 rejection.
 */

import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/db/prisma";
import { requireAuth } from "@/lib/auth/rbac";
import { readStoredFile, verifySignedAccessToken } from "@/lib/server/storage";
import { Logger } from "@/lib/server/logger";

const log = Logger.child("api/products/[id]/documents/[documentId]/download");

const GOVERNMENT_ROLES = ["SUPER_ADMIN", "ADMIN", "GOVERNMENT_OFFICIAL", "TAX_OFFICER", "AUDITOR"];

export async function GET(
  req: NextRequest,
  { params }: { params: Promise<{ id: string; documentId: string }> }
) {
  // Require authentication — no anonymous document access
  const auth = await requireAuth(req);
  if (!auth.authorized || !auth.user) return auth.errorResponse!;

  const { user } = auth;

  try {
    const { id: productId, documentId } = await params;
    const { searchParams } = new URL(req.url);
    const token = searchParams.get("token");

    if (!token) {
      return NextResponse.json(
        { error: "Access denied: A signed access token is required to download private documents." },
        { status: 403 }
      );
    }

    // Verify the signed token
    const payload = verifySignedAccessToken(token);
    if (!payload) {
      return NextResponse.json(
        { error: "Access denied: Invalid or expired access token. Request a new download link." },
        { status: 403 }
      );
    }

    // Ensure token was issued for this specific document
    if (payload.documentId !== documentId) {
      log.error("Token/document mismatch — possible IDOR attempt", {
        tokenDocumentId: payload.documentId,
        requestedDocumentId: documentId,
        userId: user.id,
      });
      return NextResponse.json(
        { error: "Access denied: Token is not valid for this document." },
        { status: 403 }
      );
    }

    // Fetch document record for additional ownership verification
    const document = await prisma.productDocument.findFirst({
      where: { id: documentId, productId },
      include: { product: { include: { seller: true } } },
    });

    if (!document) {
      return NextResponse.json({ error: "Document not found." }, { status: 404 });
    }

    // Final access check: must be owner seller OR a government/admin role
    const isGovt = GOVERNMENT_ROLES.includes(user.role);
    const isOwner = document.product.seller?.userId === user.id;

    if (!isGovt && !isOwner) {
      log.error("Unauthorized document download attempt", {
        documentId,
        userId: user.id,
        productId,
      });
      return NextResponse.json(
        { error: "Access denied: You do not have permission to download this document." },
        { status: 403 }
      );
    }

    // Read the file from private storage
    const buffer = readStoredFile(payload.storageReference);
    if (!buffer) {
      log.error("Document file missing from private storage", {
        documentId,
        storageReference: payload.storageReference,
      });
      return NextResponse.json(
        { error: "Document file not found in storage. Please re-upload." },
        { status: 404 }
      );
    }

    log.info("Private document served", {
      documentId,
      documentType: document.documentType,
      servedTo: user.id,
      userRole: user.role,
    });

    return new NextResponse(buffer as unknown as BodyInit, {
      status: 200,
      headers: {
        "Content-Type": document.mimeType,
        "Content-Length": String(buffer.byteLength),
        "Content-Disposition": `attachment; filename="${document.originalFilename}"`,
        // Hard no-cache and no-store for private government documents
        "Cache-Control": "no-store, no-cache, must-revalidate, private",
        "Pragma": "no-cache",
        "X-Content-Type-Options": "nosniff",
        "X-Frame-Options": "DENY",
        // Never let CDNs or proxies cache private documents
        "Surrogate-Control": "no-store",
      },
    });
  } catch (err) {
    log.error("GET document download failed", err);
    return NextResponse.json({ error: "Failed to serve document." }, { status: 500 });
  }
}
