import { User, Organization } from "@/lib/db/types";

export const SEED_ORGS: Record<string, Organization> = {
  org_gov_01: {
    id: "org_gov_01",
    name: "National Revenue & Customs Authority (Gov)",
    type: "GOVERNMENT",
    taxPin: "GOV-TAX-0001",
    licenseNumber: "GOV-LIC-2026-X",
    jurisdiction: "Central Federal Revenue Service",
    verified: true,
    address: "Federal Secretariat Complex, Treasury Block",
    contactEmail: "oversight@gov-revenue.org",
    createdAt: "2024-01-01T00:00:00.000Z",
  },
  org_mfg_01: {
    id: "org_mfg_01",
    name: "Apex BioTech & Consumer Goods Mfg Ltd",
    type: "MANUFACTURER",
    taxPin: "MFG-PAN-9948201",
    licenseNumber: "MFG-IND-8849-01",
    jurisdiction: "Industrial Manufacturing Zone B",
    verified: true,
    address: "Plot 42, High-Tech Industrial Hub, Sector 9",
    contactEmail: "compliance@apexbiotech.com",
    createdAt: "2024-03-15T08:30:00.000Z",
  },
  org_imp_01: {
    id: "org_imp_01",
    name: "Pacific Horizon Logistics & Importers Corp",
    type: "IMPORTER",
    taxPin: "IMP-PAN-4410982",
    licenseNumber: "IMP-CUST-7721-04",
    jurisdiction: "Customs Dry Port Clearance Terminal A",
    verified: true,
    address: "Cargo Terminal Gate 3, International Port Complex",
    contactEmail: "manifest@pacifichorizon.com",
    createdAt: "2024-04-10T10:15:00.000Z",
  },
  org_biz_01: {
    id: "org_biz_01",
    name: "Metro Retail Distribution & SuperMart Pvt Ltd",
    type: "RETAILER_DISTRIBUTOR",
    taxPin: "BIZ-VAT-8823104",
    licenseNumber: "RET-REG-3391-22",
    jurisdiction: "Metropolitan Commercial District",
    verified: true,
    address: "Avenue Mall, Commercial Plaza 104",
    contactEmail: "accounts@metroretail.com",
    createdAt: "2024-05-01T09:00:00.000Z",
  },
  org_audit_01: {
    id: "org_audit_01",
    name: "Sterling & Vance Independent Fiscal Auditors LLP",
    type: "AUDIT_FIRM",
    taxPin: "AUD-PAN-1102938",
    licenseNumber: "ICAI-AUD-99120",
    jurisdiction: "Chartered Forensic Registry",
    verified: true,
    address: "Financial Tower 8, Suite 1200",
    contactEmail: "audit-desk@sterlingvance.com",
    createdAt: "2024-02-20T11:45:00.000Z",
  },
  org_consumer_01: {
    id: "org_consumer_01",
    name: "Public Consumer Registry",
    type: "CONSUMER",
    taxPin: "N/A",
    licenseNumber: "N/A",
    jurisdiction: "National Citizen Portal",
    verified: true,
    address: "Public Domain",
    contactEmail: "public@consumer-protection.gov",
    createdAt: "2024-01-01T00:00:00.000Z",
  },
};

/**
 * SEED_USERS — 7 distinct roles.
 *
 * SUPER_ADMIN  = The Government Authority (single top-level role; replaces the former
 *               separate SUPER_ADMIN + GOVERNMENT_ADMIN split).
 * BUSINESS_OWNER has been removed — retail stores are registered and managed by
 *               the government admin. Store staff operate as BUSINESS_EMPLOYEE only.
 */
export const SEED_USERS: User[] = [
  {
    id: "usr_super_01",
    email: "admin@veriprice.gov",
    name: "Sarah Vance",
    role: "SUPER_ADMIN",
    orgId: "org_gov_01",
    organizationName: "National Revenue & Customs Authority (Gov)",
    designation: "Director General — National Revenue, Fiscal Policy & Platform Administration",
    status: "ACTIVE",
    createdAt: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "usr_tax_01",
    email: "taxofficer@veriprice.gov",
    name: "Officer Marcus Sterling",
    role: "TAX_OFFICER",
    orgId: "org_gov_01",
    organizationName: "National Revenue & Customs Authority (Gov)",
    designation: "Chief VAT & Anti-Smuggling Enforcement Officer",
    status: "ACTIVE",
    createdAt: "2024-01-10T00:00:00.000Z",
  },
  {
    id: "usr_mfg_01",
    email: "manufacturer@apexbiotech.com",
    name: "Elena Rostova",
    role: "MANUFACTURER",
    orgId: "org_mfg_01",
    organizationName: "Apex BioTech & Consumer Goods Mfg Ltd",
    designation: "VP of Quality Assurance & Production Operations",
    status: "ACTIVE",
    createdAt: "2024-03-15T00:00:00.000Z",
  },
  {
    id: "usr_imp_01",
    email: "importer@pacifichorizon.com",
    name: "David Chen",
    role: "IMPORTER",
    orgId: "org_imp_01",
    organizationName: "Pacific Horizon Logistics & Importers Corp",
    designation: "Head of Customs Manifests & Cross-Border Logistics",
    status: "ACTIVE",
    createdAt: "2024-04-10T00:00:00.000Z",
  },
  {
    id: "usr_biz_emp_01",
    email: "cashier@metroretail.com",
    name: "Rohan Joshi",
    role: "BUSINESS_EMPLOYEE",
    orgId: "org_biz_01",
    organizationName: "Metro Retail Distribution & SuperMart Pvt Ltd",
    employeeCode: "METRO-EMP-504",
    designation: "Senior POS Operator & Inventory Gatekeeper",
    status: "ACTIVE",
    createdAt: "2024-05-15T00:00:00.000Z",
  },
  {
    id: "usr_auditor_01",
    email: "auditor@sterlingvance.com",
    name: "Arthur Pendelton",
    role: "AUDITOR",
    orgId: "org_audit_01",
    organizationName: "Sterling & Vance Independent Fiscal Auditors LLP",
    designation: "Senior Forensic Provenance & Tax Auditor",
    status: "ACTIVE",
    createdAt: "2024-02-20T00:00:00.000Z",
  },
  {
    id: "usr_consumer_01",
    email: "consumer@citizens.org",
    name: "Maya Lin",
    role: "CONSUMER",
    orgId: "org_consumer_01",
    organizationName: "Public Consumer Registry",
    designation: "Verified Citizen Consumer",
    status: "ACTIVE",
    createdAt: "2024-06-01T00:00:00.000Z",
  },
];

export const ROLE_DETAILS: Record<
  string,
  { label: string; badgeColor: string; description: string; homeRoute: string }
> = {
  SUPER_ADMIN: {
    label: "Government Admin",
    badgeColor: "bg-[#1b4332] text-white border border-[#143621]",
    description:
      "Single government authority: national tax policy, statutory MRP ceilings, tenant licensing, system administration, and full audit oversight.",
    homeRoute: "/admin",
  },
  TAX_OFFICER: {
    label: "Tax Officer",
    badgeColor: "bg-[#fbf3e8] text-[#8a5b14] border border-[#eeddc2]",
    description: "VAT reconciliation audits, customs verification, tax fraud investigations, and penalty enforcement.",
    homeRoute: "/tax-engine",
  },
  MANUFACTURER: {
    label: "Manufacturer",
    badgeColor: "bg-[#eaf0ec] text-[#2d5a45] border border-[#c1d3c8]",
    description: "Production batch registration, DPP QR minting, factory dispatch manifests, and ex-factory tax declaration.",
    homeRoute: "/manufacturer",
  },
  IMPORTER: {
    label: "Importer",
    badgeColor: "bg-[#eef2f6] text-[#2b4c6f] border border-[#d0dbe7]",
    description: "Customs declaration, Port of Entry clearances, import duty calculation, and consignment transfers.",
    homeRoute: "/importer",
  },
  BUSINESS_EMPLOYEE: {
    label: "Retail Store Staff",
    badgeColor: "bg-[#f6f5f2] text-[#55524c] border border-[#e2ded6]",
    description:
      "Store staff (registered & managed by Government Admin). Scoped to POS checkouts, barcode scanning, inventory receipt, and e-invoice issuance within their licensed outlet.",
    homeRoute: "/business",
  },
  AUDITOR: {
    label: "Auditor",
    badgeColor: "bg-[#fbeeed] text-[#8c322c] border border-[#f2cfcd]",
    description: "Read-only fiscal provenance ledger inspection, supply chain integrity audits, and anomaly reports.",
    homeRoute: "/reports",
  },
  CONSUMER: {
    label: "Consumer",
    badgeColor: "bg-[#f0f4f1] text-[#2d5a45] border border-[#d2ded5]",
    description: "Public product authenticity scans, Digital Product Passport verification, and counterfeit whistleblower reports.",
    homeRoute: "/verify",
  },
};
